-- Calculate the total revenue generated by each seller and rank them revenue wise.

select 
	seller.seller_id as Seller_ID, 
    round(sum(order_items.price),2) as Revenue,
    dense_rank() over(order by sum(order_items.price) desc) as Ranking 
from seller join 
	order_items 
    on
    seller.seller_id = order_items.seller_id
group by seller.seller_id;